# Manual Identifier Conversion Example

In [1]:
0

0

In [2]:
%load_ext autoreload
%autoreload 2

In [ ]:
import sys

sys.path.append("/Users/kemalinecik/git_nosync/master_idtrack/idtrack")

In [4]:
import os
import pickle
import subprocess
import time

import idtrack
import pandas as pd
import scanpy as sc

In [5]:
from idtrack._external_mappers import convert_ids

In [7]:
from idtrack._external_mappers._ortholog import align_ortholog_pair_with_features
import gget

In [9]:
align_ortholog_pair_with_features(
    query_ensembl_id = "ENSG00000141510",
    target_species = "homo_sapiens",
    use_super5 = True,
    embedding_model_name = None,
    verbose = True,
)

16:41:03 - INFO - Getting species ID for gene ENSG00000141510 from Bgee
16:41:03 - INFO - Getting orthologs for gene ENSG00000141510 from Bgee

ValueError: No orthologs found in Bgee for query gene 'ENSG00000141510' and target species 'homo_sapiens' (canonical: 'hsapiens', genus: 'Homo', species: 'sapiens').

In [31]:
import gget

In [33]:
s1 = gget.seq("ENSG00000141510", translate=True)
s2 = gget.seq("ENSSSCG00000017950", translate=True)

15:00:58 - INFO - Requesting amino acid sequence of the canonical transcript ENST00000269305 of gene ENSG00000141510 from UniProt.
15:00:58 - INFO - Requesting amino acid sequence of the canonical transcript ENSSSCT00000063943 of gene ENSSSCG00000017950 from UniProt.
15:00:59 - WARNING - No reviewed UniProt results were found for ID ENSSSCT00000063943. Returning all unreviewed results.

In [35]:
s1

['>ENST00000269305 uniprot_id: P04637 ensembl_id: ENST00000269305 gene_name: TP53 organism: Homo sapiens sequence_length: 393',
 'MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELPPGSTKRALPNNTSSSPQPKKKPLDGEYFTLQIRGRERFEMFRELNEALELKDAQAGKEPGGSRAHSSHLKSKKGQSTSRHKKLMFKTEGPDSD']

In [36]:
s2

['>ENSSSCT00000063943 uniprot_id: A0A287B3I9 ensembl_id: ENSSSCT00000063943 gene_name: TP53 organism: Sus scrofa sequence_length: 395',
 'MEESQSELGVEPPLSQETFSDLGLGGWGAGLLTPVVPIHPQSSELSLAAVNDLLLSPVTNWLDENPDDASRVPAPPAATAPAPAAPAPATSWPLSSFVPSQKTYPGSYDFRLGFLHSGTAKSVTCTYSPALNKLFCQLAKTCPVQLWVSSPPPPGTRVRAMAIYKKSEYMTEVVRRCPHHERSSDYSDGLAPPQHLIRVEGNLRAEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNFMCNSSCMGGMNRRPILTIITLEDASGNLLGRNSFEVRVCACPGRDRRTEEENFLKKGQSCPEPPPGSTKRALPTSTSSSPVQKKKPLDGEYFTLQIRGRERFEMFRELNDALELKDAQTARESGENRAHSSHLKSKKGQSPSRHKKPMFKREGPDSD']

In [ ]:
gget.muscle([s1[1], s2[1]], super5=True)

15:02:41 - INFO - MUSCLE compiled.
15:02:41 - INFO - MUSCLE aligning...

In [26]:
f = gget.bgee("ENSG00000141510",
    type="orthologs",
    json=False,
    verbose=True
)

sorted((f["genus"] + " " + f["species"]).to_list())

14:10:02 - INFO - Getting species ID for gene ENSG00000141510 from Bgee
14:10:02 - INFO - Getting orthologs for gene ENSG00000141510 from Bgee

['Anguilla anguilla',
 'Anguilla anguilla',
 'Astyanax mexicanus',
 'Bos taurus',
 'Bos taurus',
 'Bos taurus',
 'Bos taurus',
 'Bos taurus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Callithrix jacchus',
 'Canis lupus familiaris',
 'Canis lupus familiaris',
 'Canis lupus familiaris',
 'Canis lupus familiaris',
 'Canis lupus familiaris',
 'Capra hircus',
 'Capra hircus',
 'Capra hircus',
 'Capra hircus',
 'Capra hircus',
 'Cavia porcellus',
 'Cavia porcellus',
 'Cavia porcellus',
 'Cavia porcellus',
 'Cavia porcellus',
 'Cavia porcellus',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Cercocebus atys',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Chlorocebus sabaeus',
 'Danio rerio',
 'Danio rerio',
 'Equus caballus',
 'Equus caballus',
 'Equus caballus',
 'Equus caballus',
 'Equus caballus',
 'Esox lucius',
 'Felis catus',
 'Felis catus',
 'Felis catus',
 'Felis catus',
 'Felis catus',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Gorilla gorilla',
 'Latimeria chalumnae',
 'Latimeria chalumnae',
 'Lepisosteus oculatus',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca fascicularis',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Macaca mulatta',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Manis javanica',
 'Microcebus murinus',
 'Microcebus murinus',
 'Microcebus murinus',
 'Microcebus murinus',
 'Microcebus murinus',
 'Microcebus murinus',
 'Microcebus murinus',
 'Mus musculus',
 'Mus musculus',
 'Mus musculus',
 'Mus musculus',
 'Mus musculus',
 'Mus musculus',
 'Ornithorhynchus anatinus',
 'Ornithorhynchus anatinus',
 'Ornithorhynchus anatinus',
 'Ornithorhynchus anatinus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Oryctolagus cuniculus',
 'Ovis aries',
 'Ovis aries',
 'Ovis aries',
 'Ovis aries',
 'Ovis aries',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan paniscus',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Pan troglodytes',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Papio anubis',
 'Rattus norvegicus',
 'Rattus norvegicus',
 'Rattus norvegicus',
 'Rattus norvegicus',
 'Rattus norvegicus',
 'Rattus norvegicus',
 'Salmo salar',
 'Sus scrofa',
 'Sus scrofa',
 'Sus scrofa',
 'Sus scrofa',
 'Sus scrofa',
 'Xenopus tropicalis',
 'Xenopus tropicalis',
 'Xenopus tropicalis']

In [28]:
f[f["genus"]=="Sus"]

                gene_id gene_name  species_id genus species
49   ENSSSCG00000017950      TP53        9823   Sus  scrofa
73   ENSSSCG00000017950      TP53        9823   Sus  scrofa
98   ENSSSCG00000017950      TP53        9823   Sus  scrofa
124  ENSSSCG00000017950      TP53        9823   Sus  scrofa
153  ENSSSCG00000017950      TP53        9823   Sus  scrofa

In [6]:
ids = ["ENSG00000141510.17", "ENSG00000141510", "ENSG00000157764", "ENST00000269305", "TP53", "7157", "Q96A54"]

In [7]:
df_arch2 = convert_ids(
    ids,
    "ensembl_gene",
    "hgnc_symbol",
    method="pybiomart",
    species="hsapiens"
)
df_arch2

pybiomart: 100%|█████████████████████████████████████████████████████| 6/6 [00:00<00:00, 16.51ids/s]

,input_id,input_db,mapping,output_id,output_db,method,release_used
0,ENSG00000141510,ensembl_gene,1:1,TP53,hgnc_symbol,pybiomart,http://www.ensembl.org
1,ENSG00000157764,ensembl_gene,1:1,BRAF,hgnc_symbol,pybiomart,http://www.ensembl.org
2,ENST00000269305,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org
3,TP53,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org
4,7157,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org
5,Q96A54,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org

In [8]:
df_arch2 = convert_ids(
    ids,
    "ensembl_gene",
    "uniprot",
    method="pybiomart",
    species="hsapiens",
    release_for_pybiomart=104,
    
)
df_arch2

pybiomart: 100%|█████████████████████████████████████████████████████| 6/6 [00:00<00:00, 17.79ids/s]

,input_id,input_db,mapping,output_id,output_db,method,release_used
0,ENSG00000141510,ensembl_gene,1:1,P04637,uniprot,pybiomart,http://may2021.archive.ensembl.org
1,ENSG00000141510,ensembl_gene,1:1,NaN,uniprot,pybiomart,http://may2021.archive.ensembl.org
2,ENSG00000157764,ensembl_gene,1:1,P15056,uniprot,pybiomart,http://may2021.archive.ensembl.org
3,ENSG00000157764,ensembl_gene,1:1,NaN,uniprot,pybiomart,http://may2021.archive.ensembl.org
4,ENST00000269305,ensembl_gene,1:0,None,uniprot,pybiomart,http://may2021.archive.ensembl.org
5,TP53,ensembl_gene,1:0,None,uniprot,pybiomart,http://may2021.archive.ensembl.org
6,7157,ensembl_gene,1:0,None,uniprot,pybiomart,http://may2021.archive.ensembl.org
7,Q96A54,ensembl_gene,1:0,None,uniprot,pybiomart,http://may2021.archive.ensembl.org

In [9]:
df = convert_ids(
    ids, 
    "ensembl_gene",
    "hgnc_symbol", 
    method="gprofiler", 
    species="hsapiens",
    drop_metadata_json_column=False
)
df

gprofiler: 100%|█████████████████████████████████████████████████████| 6/6 [00:00<00:00, 11.93ids/s]

,input_id,input_db,mapping,output_id,output_db,method,release_used,metadata_json
0,ENSG00000141510,ensembl_gene,1:1,TP53,hgnc_symbol,gprofiler,None,"{""n_incoming"":1,""n_converted"":1,""name"":""TP53"",..."
1,ENSG00000157764,ensembl_gene,1:1,BRAF,hgnc_symbol,gprofiler,None,"{""n_incoming"":2,""n_converted"":1,""name"":""BRAF"",..."
2,ENST00000269305,ensembl_gene,1:0,None,hgnc_symbol,gprofiler,None,{}
3,TP53,ensembl_gene,1:0,None,hgnc_symbol,gprofiler,None,{}
4,7157,ensembl_gene,1:0,None,hgnc_symbol,gprofiler,None,{}
5,Q96A54,ensembl_gene,1:0,None,hgnc_symbol,gprofiler,None,{}

In [10]:
df.iloc[0]["metadata_json"]

'{"n_incoming":1,"n_converted":1,"name":"TP53","description":"tumor protein p53 [Source:HGNC Symbol;Acc:HGNC:11998]","namespaces":"ARRAYEXPRESS,ENSG,HPA,HPA_ACC","query":"query_1"}'

In [12]:
convert_ids(
    ["7157", "1956"], 
    "entrez_gene", 
    "uniprot", 
    method="mygene",
    species="hsapiens",
)

mygene: 100%|████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.27s/ids]

   input_id     input_db mapping   output_id output_db  method release_used
0      7157  entrez_gene     1:n  A0A087WT22   uniprot  mygene         None
1      7157  entrez_gene     1:n  A0A087WXZ1   uniprot  mygene         None
2      7157  entrez_gene     1:n  A0A087X1Q1   uniprot  mygene         None
3      7157  entrez_gene     1:n  A0A0U1RQC9   uniprot  mygene         None
4      7157  entrez_gene     1:n  A0A386NBZ1   uniprot  mygene         None
5      7157  entrez_gene     1:n  A0AAQ5BHX5   uniprot  mygene         None
6      7157  entrez_gene     1:n  A0AAQ5BHY1   uniprot  mygene         None
7      7157  entrez_gene     1:n  A0AAQ5BHZ9   uniprot  mygene         None
8      7157  entrez_gene     1:n      E7EQX7   uniprot  mygene         None
9      7157  entrez_gene     1:n      E9PFT5   uniprot  mygene         None
10     7157  entrez_gene     1:n      H2EHT1   uniprot  mygene         None
11     7157  entrez_gene     1:n      I3L0W9   uniprot  mygene         None
12     7157  entrez_gene     1:n      J3KP33   uniprot  mygene         None
13     7157  entrez_gene     1:n      K7PPA8   uniprot  mygene         None
14     7157  entrez_gene     1:n      P04637   uniprot  mygene         None
15     7157  entrez_gene     1:n      Q53GA5   uniprot  mygene         None
16     7157  entrez_gene     1:n      S4R334   uniprot  mygene         None
17     1956  entrez_gene     1:n  A0A8V8TPW8   uniprot  mygene         None
18     1956  entrez_gene     1:n      B7Z2I3   uniprot  mygene         None
19     1956  entrez_gene     1:n      C9JYS6   uniprot  mygene         None
20     1956  entrez_gene     1:n      E7BSV0   uniprot  mygene         None
21     1956  entrez_gene     1:n      F2YGG7   uniprot  mygene         None
22     1956  entrez_gene     1:n      P00533   uniprot  mygene         None
23     1956  entrez_gene     1:n      Q504U8   uniprot  mygene         None

In [11]:
convert_ids(
    ids, 
    "ensembl_gene", 
    "hgnc_symbol", 
    method="mygene", 
    species="hsapiens",
)

mygene: 100%|████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.54ids/s]

,input_id,input_db,mapping,output_id,output_db,method,release_used
0,ENSG00000141510,ensembl_gene,1:1,TP53,hgnc_symbol,mygene,None
1,ENSG00000157764,ensembl_gene,1:1,BRAF,hgnc_symbol,mygene,None
2,ENST00000269305,ensembl_gene,1:0,None,hgnc_symbol,mygene,None
3,TP53,ensembl_gene,1:0,None,hgnc_symbol,mygene,None
4,7157,ensembl_gene,1:0,None,hgnc_symbol,mygene,None
5,Q96A54,ensembl_gene,1:0,None,hgnc_symbol,mygene,None

In [12]:
convert_ids(
    ids, 
    "ensembl_gene", 
    "hgnc_symbol", 
    method="gget", 
    species="hsapiens",
)

gget: 100%|██████████████████████████████████████████████████████████| 6/6 [00:40<00:00,  6.73s/ids]

,input_id,input_db,mapping,output_id,output_db,method,release_used
0,ENSG00000141510,ensembl_gene,1:1,TP53,hgnc_symbol,gget,None
1,ENSG00000157764,ensembl_gene,1:1,BRAF,hgnc_symbol,gget,None
2,ENST00000269305,ensembl_gene,1:1,TP53,hgnc_symbol,gget,None
3,TP53,ensembl_gene,1:0,None,hgnc_symbol,gget,None
4,7157,ensembl_gene,1:0,None,hgnc_symbol,gget,None
5,Q96A54,ensembl_gene,1:0,None,hgnc_symbol,gget,None

In [13]:
convert_ids(
    ids, 
    "ensembl_gene", 
    "hgnc_symbol", 
    method="pybiomart", 
    species="hsapiens",
)

pybiomart: 100%|█████████████████████████████████████████████████████| 6/6 [00:00<00:00, 17.51ids/s]

,input_id,input_db,mapping,output_id,output_db,method,release_used
0,ENSG00000141510,ensembl_gene,1:1,TP53,hgnc_symbol,pybiomart,http://www.ensembl.org
1,ENSG00000157764,ensembl_gene,1:1,BRAF,hgnc_symbol,pybiomart,http://www.ensembl.org
2,ENST00000269305,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org
3,TP53,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org
4,7157,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org
5,Q96A54,ensembl_gene,1:0,None,hgnc_symbol,pybiomart,http://www.ensembl.org