# Experiment

In [1]:
0

0

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import gc
import os
import pathlib
import subprocess
import sys
import pickle
import shutil
import json
import glob
import re
import tempfile
from pathlib import Path
from typing import Iterable

docs_dir = str(pathlib.Path(os.getcwd()).resolve().parents[0])
sys.path.append(docs_dir)
print(docs_dir)

from src.install_cellranger import install_cellranger
from src.download_references import download_references
from src.build_cellranger_mkref import build_cellranger_mkref
from src.fastq_datasets import fastq_datasets
from src.download_fastq import download_fastq
from src.run_cellranger_master import existing_outs_for_release
from src.anndata_generator import anndata_generator

/ictstr01/home/icb/kemal.inecik/work/codes/idtrack/docs/_notebooks

In [4]:
# %matplotlib inline
# %config InlineBackend.figure_format='retina'

# import matplotlib.pyplot as plt
# import seaborn as sns

# # Important to have consistent figures across platforms:
# _rcparams_path = os.path.join(docs_dir, "figure_rcparams", "rcparams.pickle")
# with open(_rcparams_path, "rb") as file:
#     _rcparams = pickle.load(file)
# plt.rcParams.update(_rcparams)

# Preparation

## Install cellranger

In [5]:
cellranger_params = dict(
    version="9.0.1",
    expected_md5="2efec98bff01f7a59edaf43724fae13f",
    url="https://cf.10xgenomics.com/releases/cell-exp/cellranger-9.0.1.tar.gz?Expires=1756836323&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=kjLqu7Mer5A0F4hV1PlJQXFGoY0pJZC8OsPilkGkIBOdxG~crQI5eLMSvV~cZzx0u94PrhZvlXofddsjzhvFXe3mPd2bauIyP5RxITf7QgpHWeZ6hNFhLI9CD5jJXgGs0bzhNhSEquxlLjHH~W3v7zpwk5mzV7jgD7tCwd00C4q-yRtwNefer~ZV7p01FwOIlo6dckef7dMgDIb~6FBuGlkDbyChbJOWITXSGyxz7IwRkFIt9C4X2bsPQ29n3I0gX3zVIAbavgKVC0ZOk0lUx6SucGUQZbhQeTvLysWDhRldj7TrYn9ZoJpo8fz50JMSTn9o3QNatz0rBs-DQasyNg__",
    apps_dir=pathlib.Path("/home/icb/kemal.inecik/tools/apps").expanduser(),
    tmp_dir=pathlib.Path("/home/icb/kemal.inecik/tools/tmp").expanduser(),
)

In [5]:
cellranger_bin = install_cellranger(**cellranger_params)

[cellranger] Downloading with curl to /ictstr01/home/icb/kemal.inecik/tools/tmp/cellranger-9.0.1.tar.gz ...
[cellranger] MD5 (python) = 2efec98bff01f7a59edaf43724fae13f
[cellranger] MD5 (md5sum) = 2efec98bff01f7a59edaf43724fae13f
[cellranger] Extracting with tar to /ictstr01/home/icb/kemal.inecik/tools/apps ...
[cellranger] Done. Installed at: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1
[cellranger] Tarball kept at: /ictstr01/home/icb/kemal.inecik/tools/tmp/cellranger-9.0.1.tar.gz

In [6]:
cellranger_bin = install_cellranger(**cellranger_params)
os.environ["PATH"] = f"{cellranger_bin.parent}:{os.environ['PATH']}"
print("bin:", cellranger_bin)
print("version:", subprocess.run([str(cellranger_bin), "--version"], text=True, capture_output=True).stdout)

[cellranger] Found existing install: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/cellranger
bin: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/cellranger
version: cellranger cellranger-9.0.1

## Download annotation sources

In [7]:
download_references_params = dict(
    workdir = pathlib.Path("/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard"),
    releases = range(80, 115),  # 80..114 inclusive
    fasta_name = "Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz",
    gunzip=True,        
    keep_gz=True,       
)

In [7]:
paths_references = download_references(silent=False, **download_references_params)

[release 80] Downloaded: Homo_sapiens.GRCh38.80.gtf.gz
[release 80] Gunzipped: Homo_sapiens.GRCh38.80.gtf
[release 80] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 80] Renamed: Homo_sapiens.GRCh38.80.dna.primary_assembly.fa.gz
[release 80] Gunzipped: Homo_sapiens.GRCh38.80.dna.primary_assembly.fa
[release 81] Downloaded: Homo_sapiens.GRCh38.81.gtf.gz
[release 81] Gunzipped: Homo_sapiens.GRCh38.81.gtf
[release 81] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 81] Renamed: Homo_sapiens.GRCh38.81.dna.primary_assembly.fa.gz
[release 81] Gunzipped: Homo_sapiens.GRCh38.81.dna.primary_assembly.fa
[release 82] Downloaded: Homo_sapiens.GRCh38.82.gtf.gz
[release 82] Gunzipped: Homo_sapiens.GRCh38.82.gtf
[release 82] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 82] Renamed: Homo_sapiens.GRCh38.82.dna.primary_assembly.fa.gz
[release 82] Gunzipped: Homo_sapiens.GRCh38.82.dna.primary_assembly.fa
[release 83] Downloaded: Homo_sapiens.GRCh38.83.gtf.gz
[release 83] Gunzipped: Homo_sapiens.GRCh38.83.gtf
[release 83] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 83] Renamed: Homo_sapiens.GRCh38.83.dna.primary_assembly.fa.gz
[release 83] Gunzipped: Homo_sapiens.GRCh38.83.dna.primary_assembly.fa
[release 84] Downloaded: Homo_sapiens.GRCh38.84.gtf.gz
[release 84] Gunzipped: Homo_sapiens.GRCh38.84.gtf
[release 84] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 84] Renamed: Homo_sapiens.GRCh38.84.dna.primary_assembly.fa.gz
[release 84] Gunzipped: Homo_sapiens.GRCh38.84.dna.primary_assembly.fa
[release 85] Downloaded: Homo_sapiens.GRCh38.85.gtf.gz
[release 85] Gunzipped: Homo_sapiens.GRCh38.85.gtf
[release 85] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 85] Renamed: Homo_sapiens.GRCh38.85.dna.primary_assembly.fa.gz
[release 85] Gunzipped: Homo_sapiens.GRCh38.85.dna.primary_assembly.fa
[release 86] Downloaded: Homo_sapiens.GRCh38.86.gtf.gz
[release 86] Gunzipped: Homo_sapiens.GRCh38.86.gtf
[release 86] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 86] Renamed: Homo_sapiens.GRCh38.86.dna.primary_assembly.fa.gz
[release 86] Gunzipped: Homo_sapiens.GRCh38.86.dna.primary_assembly.fa
[release 87] Downloaded: Homo_sapiens.GRCh38.87.gtf.gz
[release 87] Gunzipped: Homo_sapiens.GRCh38.87.gtf
[release 87] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 87] Renamed: Homo_sapiens.GRCh38.87.dna.primary_assembly.fa.gz
[release 87] Gunzipped: Homo_sapiens.GRCh38.87.dna.primary_assembly.fa
[release 88] Downloaded: Homo_sapiens.GRCh38.88.gtf.gz
[release 88] Gunzipped: Homo_sapiens.GRCh38.88.gtf
[release 88] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 88] Renamed: Homo_sapiens.GRCh38.88.dna.primary_assembly.fa.gz
[release 88] Gunzipped: Homo_sapiens.GRCh38.88.dna.primary_assembly.fa
[release 89] Downloaded: Homo_sapiens.GRCh38.89.gtf.gz
[release 89] Gunzipped: Homo_sapiens.GRCh38.89.gtf
[release 89] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 89] Renamed: Homo_sapiens.GRCh38.89.dna.primary_assembly.fa.gz
[release 89] Gunzipped: Homo_sapiens.GRCh38.89.dna.primary_assembly.fa
[release 90] Downloaded: Homo_sapiens.GRCh38.90.gtf.gz
[release 90] Gunzipped: Homo_sapiens.GRCh38.90.gtf
[release 90] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 90] Renamed: Homo_sapiens.GRCh38.90.dna.primary_assembly.fa.gz
[release 90] Gunzipped: Homo_sapiens.GRCh38.90.dna.primary_assembly.fa
[release 91] Downloaded: Homo_sapiens.GRCh38.91.gtf.gz
[release 91] Gunzipped: Homo_sapiens.GRCh38.91.gtf
[release 91] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 91] Renamed: Homo_sapiens.GRCh38.91.dna.primary_assembly.fa.gz
[release 91] Gunzipped: Homo_sapiens.GRCh38.91.dna.primary_assembly.fa
[release 92] Downloaded: Homo_sapiens.GRCh38.92.gtf.gz
[release 92] Gunzipped: Homo_sapiens.GRCh38.92.gtf
[release 92] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 92] Renamed: Homo_sapiens.GRCh38.92.dna.primary_assembly.fa.gz
[release 92] Gunzipped: Homo_sapiens.GRCh38.92.dna.primary_assembly.fa
[release 93] Downloaded: Homo_sapiens.GRCh38.93.gtf.gz
[release 93] Gunzipped: Homo_sapiens.GRCh38.93.gtf
[release 93] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 93] Renamed: Homo_sapiens.GRCh38.93.dna.primary_assembly.fa.gz
[release 93] Gunzipped: Homo_sapiens.GRCh38.93.dna.primary_assembly.fa
[release 94] Downloaded: Homo_sapiens.GRCh38.94.gtf.gz
[release 94] Gunzipped: Homo_sapiens.GRCh38.94.gtf
[release 94] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 94] Renamed: Homo_sapiens.GRCh38.94.dna.primary_assembly.fa.gz
[release 94] Gunzipped: Homo_sapiens.GRCh38.94.dna.primary_assembly.fa
[release 95] Downloaded: Homo_sapiens.GRCh38.95.gtf.gz
[release 95] Gunzipped: Homo_sapiens.GRCh38.95.gtf
[release 95] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 95] Renamed: Homo_sapiens.GRCh38.95.dna.primary_assembly.fa.gz
[release 95] Gunzipped: Homo_sapiens.GRCh38.95.dna.primary_assembly.fa
[release 96] Downloaded: Homo_sapiens.GRCh38.96.gtf.gz
[release 96] Gunzipped: Homo_sapiens.GRCh38.96.gtf
[release 96] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 96] Renamed: Homo_sapiens.GRCh38.96.dna.primary_assembly.fa.gz
[release 96] Gunzipped: Homo_sapiens.GRCh38.96.dna.primary_assembly.fa
[release 97] Downloaded: Homo_sapiens.GRCh38.97.gtf.gz
[release 97] Gunzipped: Homo_sapiens.GRCh38.97.gtf
[release 97] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 97] Renamed: Homo_sapiens.GRCh38.97.dna.primary_assembly.fa.gz
[release 97] Gunzipped: Homo_sapiens.GRCh38.97.dna.primary_assembly.fa
[release 98] Downloaded: Homo_sapiens.GRCh38.98.gtf.gz
[release 98] Gunzipped: Homo_sapiens.GRCh38.98.gtf
[release 98] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 98] Renamed: Homo_sapiens.GRCh38.98.dna.primary_assembly.fa.gz
[release 98] Gunzipped: Homo_sapiens.GRCh38.98.dna.primary_assembly.fa
[release 99] Downloaded: Homo_sapiens.GRCh38.99.gtf.gz
[release 99] Gunzipped: Homo_sapiens.GRCh38.99.gtf
[release 99] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 99] Renamed: Homo_sapiens.GRCh38.99.dna.primary_assembly.fa.gz
[release 99] Gunzipped: Homo_sapiens.GRCh38.99.dna.primary_assembly.fa
[release 100] Downloaded: Homo_sapiens.GRCh38.100.gtf.gz
[release 100] Gunzipped: Homo_sapiens.GRCh38.100.gtf
[release 100] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 100] Renamed: Homo_sapiens.GRCh38.100.dna.primary_assembly.fa.gz
[release 100] Gunzipped: Homo_sapiens.GRCh38.100.dna.primary_assembly.fa
[release 101] Downloaded: Homo_sapiens.GRCh38.101.gtf.gz
[release 101] Gunzipped: Homo_sapiens.GRCh38.101.gtf
[release 101] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 101] Renamed: Homo_sapiens.GRCh38.101.dna.primary_assembly.fa.gz
[release 101] Gunzipped: Homo_sapiens.GRCh38.101.dna.primary_assembly.fa
[release 102] Downloaded: Homo_sapiens.GRCh38.102.gtf.gz
[release 102] Gunzipped: Homo_sapiens.GRCh38.102.gtf
[release 102] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 102] Renamed: Homo_sapiens.GRCh38.102.dna.primary_assembly.fa.gz
[release 102] Gunzipped: Homo_sapiens.GRCh38.102.dna.primary_assembly.fa
[release 103] Downloaded: Homo_sapiens.GRCh38.103.gtf.gz
[release 103] Gunzipped: Homo_sapiens.GRCh38.103.gtf
[release 103] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 103] Renamed: Homo_sapiens.GRCh38.103.dna.primary_assembly.fa.gz
[release 103] Gunzipped: Homo_sapiens.GRCh38.103.dna.primary_assembly.fa
[release 104] Downloaded: Homo_sapiens.GRCh38.104.gtf.gz
[release 104] Gunzipped: Homo_sapiens.GRCh38.104.gtf
[release 104] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 104] Renamed: Homo_sapiens.GRCh38.104.dna.primary_assembly.fa.gz
[release 104] Gunzipped: Homo_sapiens.GRCh38.104.dna.primary_assembly.fa
[release 105] Downloaded: Homo_sapiens.GRCh38.105.gtf.gz
[release 105] Gunzipped: Homo_sapiens.GRCh38.105.gtf
[release 105] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 105] Renamed: Homo_sapiens.GRCh38.105.dna.primary_assembly.fa.gz
[release 105] Gunzipped: Homo_sapiens.GRCh38.105.dna.primary_assembly.fa
[release 106] Downloaded: Homo_sapiens.GRCh38.106.gtf.gz
[release 106] Gunzipped: Homo_sapiens.GRCh38.106.gtf
[release 106] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 106] Renamed: Homo_sapiens.GRCh38.106.dna.primary_assembly.fa.gz
[release 106] Gunzipped: Homo_sapiens.GRCh38.106.dna.primary_assembly.fa
[release 107] Downloaded: Homo_sapiens.GRCh38.107.gtf.gz
[release 107] Gunzipped: Homo_sapiens.GRCh38.107.gtf
[release 107] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 107] Renamed: Homo_sapiens.GRCh38.107.dna.primary_assembly.fa.gz
[release 107] Gunzipped: Homo_sapiens.GRCh38.107.dna.primary_assembly.fa
[release 108] Downloaded: Homo_sapiens.GRCh38.108.gtf.gz
[release 108] Gunzipped: Homo_sapiens.GRCh38.108.gtf
[release 108] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 108] Renamed: Homo_sapiens.GRCh38.108.dna.primary_assembly.fa.gz
[release 108] Gunzipped: Homo_sapiens.GRCh38.108.dna.primary_assembly.fa
[release 109] Downloaded: Homo_sapiens.GRCh38.109.gtf.gz
[release 109] Gunzipped: Homo_sapiens.GRCh38.109.gtf
[release 109] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 109] Renamed: Homo_sapiens.GRCh38.109.dna.primary_assembly.fa.gz
[release 109] Gunzipped: Homo_sapiens.GRCh38.109.dna.primary_assembly.fa
[release 110] Downloaded: Homo_sapiens.GRCh38.110.gtf.gz
[release 110] Gunzipped: Homo_sapiens.GRCh38.110.gtf
[release 110] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 110] Renamed: Homo_sapiens.GRCh38.110.dna.primary_assembly.fa.gz
[release 110] Gunzipped: Homo_sapiens.GRCh38.110.dna.primary_assembly.fa
[release 111] Downloaded: Homo_sapiens.GRCh38.111.gtf.gz
[release 111] Gunzipped: Homo_sapiens.GRCh38.111.gtf
[release 111] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 111] Renamed: Homo_sapiens.GRCh38.111.dna.primary_assembly.fa.gz
[release 111] Gunzipped: Homo_sapiens.GRCh38.111.dna.primary_assembly.fa
[release 112] Downloaded: Homo_sapiens.GRCh38.112.gtf.gz
[release 112] Gunzipped: Homo_sapiens.GRCh38.112.gtf
[release 112] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 112] Renamed: Homo_sapiens.GRCh38.112.dna.primary_assembly.fa.gz
[release 112] Gunzipped: Homo_sapiens.GRCh38.112.dna.primary_assembly.fa
[release 113] Downloaded: Homo_sapiens.GRCh38.113.gtf.gz
[release 113] Gunzipped: Homo_sapiens.GRCh38.113.gtf
[release 113] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 113] Renamed: Homo_sapiens.GRCh38.113.dna.primary_assembly.fa.gz
[release 113] Gunzipped: Homo_sapiens.GRCh38.113.dna.primary_assembly.fa
[release 114] Downloaded: Homo_sapiens.GRCh38.114.gtf.gz
[release 114] Gunzipped: Homo_sapiens.GRCh38.114.gtf
[release 114] Downloaded: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[release 114] Renamed: Homo_sapiens.GRCh38.114.dna.primary_assembly.fa.gz
[release 114] Gunzipped: Homo_sapiens.GRCh38.114.dna.primary_assembly.fa

In [8]:
paths_references = download_references(silent=True, **download_references_params)

## Create reference for cellranger

In [9]:
build_cellranger_mkref_params = dict(
    paths_by_release = paths_references,
    cellranger_bin = cellranger_bin,
    assembly_label = "GRCh38",
    use_threads = 28
)

In [10]:
paths_cellranger_mkref = build_cellranger_mkref(silent=False, **build_cellranger_mkref_params)

[release 80] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_80/Homo_sapiens.GRCh38.80.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_80/Homo_sapiens.GRCh38.80.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 80] mkgtf OK: Homo_sapiens.GRCh38.80.filtered.gtf
[release 80] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_80 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_80/Homo_sapiens.GRCh38.80.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_80/Homo_sapiens.GRCh38.80.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_80)
[release 80] mkref FAILED — unknown error
[release 81] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_81/Homo_sapiens.GRCh38.81.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_81/Homo_sapiens.GRCh38.81.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 81] mkgtf OK: Homo_sapiens.GRCh38.81.filtered.gtf
[release 81] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_81 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_81/Homo_sapiens.GRCh38.81.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_81/Homo_sapiens.GRCh38.81.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_81)
[release 81] mkref FAILED — unknown error
[release 82] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_82/Homo_sapiens.GRCh38.82.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_82/Homo_sapiens.GRCh38.82.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 82] mkgtf OK: Homo_sapiens.GRCh38.82.filtered.gtf
[release 82] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_82 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_82/Homo_sapiens.GRCh38.82.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_82/Homo_sapiens.GRCh38.82.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_82)
[release 82] mkref OK: reference_GRCh38_82
[release 83] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_83/Homo_sapiens.GRCh38.83.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_83/Homo_sapiens.GRCh38.83.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 83] mkgtf OK: Homo_sapiens.GRCh38.83.filtered.gtf
[release 83] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_83 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_83/Homo_sapiens.GRCh38.83.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_83/Homo_sapiens.GRCh38.83.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_83)
[release 83] mkref OK: reference_GRCh38_83
[release 84] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_84/Homo_sapiens.GRCh38.84.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_84/Homo_sapiens.GRCh38.84.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 84] mkgtf OK: Homo_sapiens.GRCh38.84.filtered.gtf
[release 84] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_84 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_84/Homo_sapiens.GRCh38.84.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_84/Homo_sapiens.GRCh38.84.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_84)
[release 84] mkref OK: reference_GRCh38_84
[release 85] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_85/Homo_sapiens.GRCh38.85.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_85/Homo_sapiens.GRCh38.85.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 85] mkgtf OK: Homo_sapiens.GRCh38.85.filtered.gtf
[release 85] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_85 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_85/Homo_sapiens.GRCh38.85.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_85/Homo_sapiens.GRCh38.85.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_85)
[release 85] mkref OK: reference_GRCh38_85
[release 86] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_86/Homo_sapiens.GRCh38.86.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_86/Homo_sapiens.GRCh38.86.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 86] mkgtf OK: Homo_sapiens.GRCh38.86.filtered.gtf
[release 86] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_86 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_86/Homo_sapiens.GRCh38.86.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_86/Homo_sapiens.GRCh38.86.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_86)
[release 86] mkref OK: reference_GRCh38_86
[release 87] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_87/Homo_sapiens.GRCh38.87.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_87/Homo_sapiens.GRCh38.87.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 87] mkgtf OK: Homo_sapiens.GRCh38.87.filtered.gtf
[release 87] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_87 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_87/Homo_sapiens.GRCh38.87.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_87/Homo_sapiens.GRCh38.87.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_87)
[release 87] mkref OK: reference_GRCh38_87
[release 88] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_88/Homo_sapiens.GRCh38.88.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_88/Homo_sapiens.GRCh38.88.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 88] mkgtf OK: Homo_sapiens.GRCh38.88.filtered.gtf
[release 88] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_88 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_88/Homo_sapiens.GRCh38.88.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_88/Homo_sapiens.GRCh38.88.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_88)
[release 88] mkref OK: reference_GRCh38_88
[release 89] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_89/Homo_sapiens.GRCh38.89.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_89/Homo_sapiens.GRCh38.89.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 89] mkgtf OK: Homo_sapiens.GRCh38.89.filtered.gtf
[release 89] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_89 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_89/Homo_sapiens.GRCh38.89.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_89/Homo_sapiens.GRCh38.89.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_89)
[release 89] mkref OK: reference_GRCh38_89
[release 90] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_90/Homo_sapiens.GRCh38.90.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_90/Homo_sapiens.GRCh38.90.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 90] mkgtf OK: Homo_sapiens.GRCh38.90.filtered.gtf
[release 90] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_90 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_90/Homo_sapiens.GRCh38.90.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_90/Homo_sapiens.GRCh38.90.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_90)
[release 90] mkref OK: reference_GRCh38_90
[release 91] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_91/Homo_sapiens.GRCh38.91.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_91/Homo_sapiens.GRCh38.91.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 91] mkgtf OK: Homo_sapiens.GRCh38.91.filtered.gtf
[release 91] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_91 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_91/Homo_sapiens.GRCh38.91.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_91/Homo_sapiens.GRCh38.91.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_91)
[release 91] mkref OK: reference_GRCh38_91
[release 92] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_92/Homo_sapiens.GRCh38.92.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_92/Homo_sapiens.GRCh38.92.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 92] mkgtf OK: Homo_sapiens.GRCh38.92.filtered.gtf
[release 92] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_92 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_92/Homo_sapiens.GRCh38.92.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_92/Homo_sapiens.GRCh38.92.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_92)
[release 92] mkref OK: reference_GRCh38_92
[release 93] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_93/Homo_sapiens.GRCh38.93.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_93/Homo_sapiens.GRCh38.93.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 93] mkgtf OK: Homo_sapiens.GRCh38.93.filtered.gtf
[release 93] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_93 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_93/Homo_sapiens.GRCh38.93.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_93/Homo_sapiens.GRCh38.93.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_93)
[release 93] mkref OK: reference_GRCh38_93
[release 94] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_94/Homo_sapiens.GRCh38.94.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_94/Homo_sapiens.GRCh38.94.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 94] mkgtf OK: Homo_sapiens.GRCh38.94.filtered.gtf
[release 94] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_94 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_94/Homo_sapiens.GRCh38.94.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_94/Homo_sapiens.GRCh38.94.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_94)
[release 94] mkref OK: reference_GRCh38_94
[release 95] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_95/Homo_sapiens.GRCh38.95.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_95/Homo_sapiens.GRCh38.95.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 95] mkgtf OK: Homo_sapiens.GRCh38.95.filtered.gtf
[release 95] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_95 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_95/Homo_sapiens.GRCh38.95.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_95/Homo_sapiens.GRCh38.95.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_95)
[release 95] mkref OK: reference_GRCh38_95
[release 96] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_96/Homo_sapiens.GRCh38.96.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_96/Homo_sapiens.GRCh38.96.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 96] mkgtf OK: Homo_sapiens.GRCh38.96.filtered.gtf
[release 96] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_96 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_96/Homo_sapiens.GRCh38.96.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_96/Homo_sapiens.GRCh38.96.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_96)
[release 96] mkref OK: reference_GRCh38_96
[release 97] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_97/Homo_sapiens.GRCh38.97.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_97/Homo_sapiens.GRCh38.97.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding
[release 97] mkgtf OK: Homo_sapiens.GRCh38.97.filtered.gtf
[release 97] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkref --genome=reference_GRCh38_97 --fasta=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_97/Homo_sapiens.GRCh38.97.dna.primary_assembly.fa --genes=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_97/Homo_sapiens.GRCh38.97.filtered.gtf --nthreads=28 (cwd=/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_97)
[release 97] mkref OK: reference_GRCh38_97
[release 98] Running: /ictstr01/home/icb/kemal.inecik/tools/apps/cellranger-9.0.1/bin/cellranger mkgtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_98/Homo_sapiens.GRCh38.98.gtf /lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/references_gold_standard/GRCh38_98/Homo_sapiens.GRCh38.98.filtered.gtf --attribute=gene_biotype:protein_coding --attribute=gene_type:protein_coding

In [10]:
paths_cellranger_mkref = build_cellranger_mkref(silent=True, **build_cellranger_mkref_params)

## Download sequencing data

In [11]:
download_fastq_params = dict(
    datasets = fastq_datasets,
    working_dir = pathlib.Path("/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/fastq_raw"),
)

In [ ]:
paths_download_fastq = download_fastq(silent=False, **download_fastq_params)

Downloading: 'pbmc_1k_v3'
Downloading: 'pbmc_20k_donors1_4_multiplex_gemx_3p'
Downloading: 'pbmc_10k_5p_v3_ultima'
Downloading: 'pbmc_10k_3p_v31_si'

In [12]:
paths_download_fastq = download_fastq(silent=True, **download_fastq_params)

## Run alignments

In [13]:
override = False
datasets = ["pbmc_1k_v3"]  # you can add more later
assembly_labels = ["GRCh38"]

prior_workdir = Path("/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments").resolve()
working_dir = Path("/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments").resolve()
working_dir.mkdir(parents=True, exist_ok=True)
run_cellranger_script = Path.cwd().resolve().parent / "src" / "run_cellranger_master.py"

count = 0
errors = []

for dataset_key in paths_download_fastq:

    if dataset_key not in datasets:
        continue
    
    # (A) discover releases for the first (and only) assembly in your note, but we allow multiple
    for assembly_label in assembly_labels:
        
        for release, release_content in paths_cellranger_mkref.items():

            # if count > 0:
            #     break

            if release_content["status"] != 'done':
                print(f"[WARN] No releases discovered for assembly {assembly_label!r}, release {release!r}.")
                continue
            
            # Per your request: create a folder for each dataset / release / assembly under working_dir
            job_dir = (working_dir / dataset_key / f"{assembly_label}_{release}").resolve()
            job_dir.mkdir(parents=True, exist_ok=True)
            # Slurm log lives in the "respective" folder
            slurm_log = job_dir / f"slurm_job.log"
            # Skip if existing output (unless override)
            existing = existing_outs_for_release(working_dir, dataset_key, assembly_label, release)
            if existing and not override:
                print(f"[SKIP] Found existing metrics for {dataset_key} release {release}: {existing}")
                continue

            # Build Slurm script (kept inside the notebook cell, per your example)
            slurm_script = f"""#!/bin/bash
#SBATCH -J cr_{dataset_key}_r{release}
#SBATCH -p cpu_p
#SBATCH --qos cpu_normal
#SBATCH -c 4
#SBATCH --mem=32G
#SBATCH --nice=0
#SBATCH -t 11:50:00
#SBATCH -o {slurm_log}
#SBATCH -e {slurm_log}

echo "Start"

set -eo pipefail

echo "Environment setup"
source ~/.bashrc && conda activate idtrack_dev_env

echo "Python started"
python -u "{run_cellranger_script}" \\
  --dataset-key "{dataset_key}" \\
  --release {release} \\
  --workdir "{prior_workdir}" \\
  --results-dir "{working_dir}" \\
  --assembly-label "{assembly_label}" \\
  --cellranger-bin "{cellranger_bin}" \\
  --no-download

echo "End."
"""
            try:
                script_name = job_dir / f"slurm_job.sh"
                with open(script_name, "w") as f:
                    f.write(slurm_script)
    
                print(f"Submitting: {dataset_key} / {assembly_label} / r{release} / log {slurm_log}")
                subprocess.run(["sbatch", str(script_name)], check=False)
                count += 1
        
            finally:
                # os.remove(script_name)
                pass
                
print(f" - Number of jobs submitted: {count}")

[WARN] No releases discovered for assembly 'GRCh38', release 80.
[WARN] No releases discovered for assembly 'GRCh38', release 81.
Submitting: pbmc_1k_v3 / GRCh38 / r82 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_82/slurm_job.log
Submitted batch job 30744789
Submitting: pbmc_1k_v3 / GRCh38 / r83 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_83/slurm_job.log
Submitted batch job 30744790
Submitting: pbmc_1k_v3 / GRCh38 / r84 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_84/slurm_job.log
Submitted batch job 30744791
Submitting: pbmc_1k_v3 / GRCh38 / r85 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_85/slurm_job.log
Submitted batch job 30744792
Submitting: pbmc_1k_v3 / GRCh38 / r86 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_86/slurm_job.log
Submitted batch job 30744793
Submitting: pbmc_1k_v3 / GRCh38 / r87 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_87/slurm_job.log
Submitted batch job 30744794
Submitting: pbmc_1k_v3 / GRCh38 / r88 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_88/slurm_job.log
Submitted batch job 30744795
Submitting: pbmc_1k_v3 / GRCh38 / r89 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_89/slurm_job.log
Submitted batch job 30744796
Submitting: pbmc_1k_v3 / GRCh38 / r90 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_90/slurm_job.log
Submitted batch job 30744797
Submitting: pbmc_1k_v3 / GRCh38 / r91 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_91/slurm_job.log
Submitted batch job 30744798
Submitting: pbmc_1k_v3 / GRCh38 / r92 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_92/slurm_job.log
Submitted batch job 30744799
Submitting: pbmc_1k_v3 / GRCh38 / r93 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_93/slurm_job.log
Submitted batch job 30744800
Submitting: pbmc_1k_v3 / GRCh38 / r94 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_94/slurm_job.log
Submitted batch job 30744801
Submitting: pbmc_1k_v3 / GRCh38 / r95 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_95/slurm_job.log
Submitted batch job 30744802
Submitting: pbmc_1k_v3 / GRCh38 / r96 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_96/slurm_job.log
Submitted batch job 30744803
Submitting: pbmc_1k_v3 / GRCh38 / r97 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_97/slurm_job.log
Submitted batch job 30744804
Submitting: pbmc_1k_v3 / GRCh38 / r98 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_98/slurm_job.log
Submitted batch job 30744805
Submitting: pbmc_1k_v3 / GRCh38 / r99 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_99/slurm_job.log
Submitted batch job 30744806
Submitting: pbmc_1k_v3 / GRCh38 / r100 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/slurm_job.log
Submitted batch job 30744807
Submitting: pbmc_1k_v3 / GRCh38 / r101 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_101/slurm_job.log
Submitted batch job 30744808
Submitting: pbmc_1k_v3 / GRCh38 / r102 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_102/slurm_job.log
Submitted batch job 30744809
Submitting: pbmc_1k_v3 / GRCh38 / r103 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_103/slurm_job.log
Submitted batch job 30744810
Submitting: pbmc_1k_v3 / GRCh38 / r104 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_104/slurm_job.log
Submitted batch job 30744811
Submitting: pbmc_1k_v3 / GRCh38 / r105 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_105/slurm_job.log
Submitted batch job 30744812
Submitting: pbmc_1k_v3 / GRCh38 / r106 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_106/slurm_job.log
Submitted batch job 30744813
Submitting: pbmc_1k_v3 / GRCh38 / r107 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_107/slurm_job.log
Submitted batch job 30744814
Submitting: pbmc_1k_v3 / GRCh38 / r108 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_108/slurm_job.log
Submitted batch job 30744815
Submitting: pbmc_1k_v3 / GRCh38 / r109 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_109/slurm_job.log
Submitted batch job 30744816
Submitting: pbmc_1k_v3 / GRCh38 / r110 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_110/slurm_job.log
Submitted batch job 30744817
Submitting: pbmc_1k_v3 / GRCh38 / r111 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_111/slurm_job.log
Submitted batch job 30744818
Submitting: pbmc_1k_v3 / GRCh38 / r112 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_112/slurm_job.log
Submitted batch job 30744819
Submitting: pbmc_1k_v3 / GRCh38 / r113 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_113/slurm_job.log
Submitted batch job 30744820
Submitting: pbmc_1k_v3 / GRCh38 / r114 / log /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_114/slurm_job.log
Submitted batch job 30744821
 - Number of jobs submitted: 33

## Prepare anndata

In [13]:
anndata_generator_params = dict(
    alignments_root=Path("/lustre/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments"),
    out_root="/home/icb/kemal.inecik/lustre_workspace/idtrack_experiments/anndatas",
    keep_obs_if_it_is_filtered_by_cellranger=True
)

In [14]:
anndata_paths = anndata_generator(silent=False, **anndata_generator_params)

[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/pbmc_1k_v3_count_r100/outs (run=pbmc_1k_v3_count_r100) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_100.h5ad  shape=1221x19970
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_101/pbmc_1k_v3_count_r101/outs (run=pbmc_1k_v3_count_r101) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_101.h5ad  shape=1221x19966
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_102/pbmc_1k_v3_count_r102/outs (run=pbmc_1k_v3_count_r102) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_102.h5ad  shape=1222x19973
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_103/pbmc_1k_v3_count_r103/outs (run=pbmc_1k_v3_count_r103) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_103.h5ad  shape=1222x19962
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_104/pbmc_1k_v3_count_r104/outs (run=pbmc_1k_v3_count_r104) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_104.h5ad  shape=1222x19966
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_105/pbmc_1k_v3_count_r105/outs (run=pbmc_1k_v3_count_r105) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_105.h5ad  shape=1223x19988
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_106/pbmc_1k_v3_count_r106/outs (run=pbmc_1k_v3_count_r106) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_106.h5ad  shape=1223x19994
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_107/pbmc_1k_v3_count_r107/outs (run=pbmc_1k_v3_count_r107) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_107.h5ad  shape=1221x20023
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_108/pbmc_1k_v3_count_r108/outs (run=pbmc_1k_v3_count_r108) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_108.h5ad  shape=1220x20036
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_109/pbmc_1k_v3_count_r109/outs (run=pbmc_1k_v3_count_r109) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_109.h5ad  shape=1219x20048
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_110/pbmc_1k_v3_count_r110/outs (run=pbmc_1k_v3_count_r110) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_110.h5ad  shape=1220x20070
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_111/pbmc_1k_v3_count_r111/outs (run=pbmc_1k_v3_count_r111) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_111.h5ad  shape=1220x20073
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_112/pbmc_1k_v3_count_r112/outs (run=pbmc_1k_v3_count_r112) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_112.h5ad  shape=1219x20089
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_113/pbmc_1k_v3_count_r113/outs (run=pbmc_1k_v3_count_r113) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_113.h5ad  shape=1220x20116
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_114/pbmc_1k_v3_count_r114/outs (run=pbmc_1k_v3_count_r114) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_114.h5ad  shape=1220x20120
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_82/pbmc_1k_v3_count_r82/outs (run=pbmc_1k_v3_count_r82) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_82.h5ad  shape=1221x19808
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_83/pbmc_1k_v3_count_r83/outs (run=pbmc_1k_v3_count_r83) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_83.h5ad  shape=1222x19826
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_84/pbmc_1k_v3_count_r84/outs (run=pbmc_1k_v3_count_r84) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_84.h5ad  shape=1222x19826
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_85/pbmc_1k_v3_count_r85/outs (run=pbmc_1k_v3_count_r85) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_85.h5ad  shape=1222x19961
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_86/pbmc_1k_v3_count_r86/outs (run=pbmc_1k_v3_count_r86) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_86.h5ad  shape=1222x19961
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_87/pbmc_1k_v3_count_r87/outs (run=pbmc_1k_v3_count_r87) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_87.h5ad  shape=1222x19961
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_88/pbmc_1k_v3_count_r88/outs (run=pbmc_1k_v3_count_r88) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_88.h5ad  shape=1223x19828
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_89/pbmc_1k_v3_count_r89/outs (run=pbmc_1k_v3_count_r89) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_89.h5ad  shape=1223x19828
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_90/pbmc_1k_v3_count_r90/outs (run=pbmc_1k_v3_count_r90) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_90.h5ad  shape=1223x19847
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_91/pbmc_1k_v3_count_r91/outs (run=pbmc_1k_v3_count_r91) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_91.h5ad  shape=1223x19847
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_92/pbmc_1k_v3_count_r92/outs (run=pbmc_1k_v3_count_r92) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_92.h5ad  shape=1220x19912
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_93/pbmc_1k_v3_count_r93/outs (run=pbmc_1k_v3_count_r93) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_93.h5ad  shape=1220x19912
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_94/pbmc_1k_v3_count_r94/outs (run=pbmc_1k_v3_count_r94) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_94.h5ad  shape=1220x19951
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_95/pbmc_1k_v3_count_r95/outs (run=pbmc_1k_v3_count_r95) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_95.h5ad  shape=1220x19951
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_96/pbmc_1k_v3_count_r96/outs (run=pbmc_1k_v3_count_r96) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_96.h5ad  shape=1220x19997
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_97/pbmc_1k_v3_count_r97/outs (run=pbmc_1k_v3_count_r97) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_97.h5ad  shape=1221x19986
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_98/pbmc_1k_v3_count_r98/outs (run=pbmc_1k_v3_count_r98) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_98.h5ad  shape=1221x19976
[INFO] Building AnnData from /ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_99/pbmc_1k_v3_count_r99/outs (run=pbmc_1k_v3_count_r99) [filtered_only=True]
[OK] Wrote pbmc_1k_v3_GRCh38_99.h5ad  shape=1221x19968

In [18]:
anndata_paths = anndata_generator(silent=True, **anndata_generator_params)

In [21]:
import anndata as ad
adata114=ad.read_h5ad(anndata_paths['pbmc_1k_v3']['GRCh38']['100'])

In [22]:
adata114

AnnData object with n_obs × n_vars = 1221 × 19970
    obs: 'is_filtered_by_cellranger'
    var: 'gene_id', 'gene_symbol', 'feature_type', 'genome'
    uns: 'cellranger', 'provenance'

In [23]:
adata114.obs

                    is_filtered_by_cellranger
barcode
AAACCCAAGGAGAGTA-1                       True
AAACGCTTCAGCCCAG-1                       True
AAAGAACAGACGACTG-1                       True
AAAGAACCAATGGCAG-1                       True
AAAGAACGTCTGCAAT-1                       True
...                                       ...
TTTCCTCTCTCTTGCG-1                       True
TTTGATCTCTTTGGAG-1                       True
TTTGGTTAGTAACCTC-1                       True
TTTGGTTGTAGAATAC-1                       True
TTTGTTGCAATTAGGA-1                       True

[1221 rows x 1 columns]

In [24]:
adata114.var

,gene_id,gene_symbol,feature_type,genome
feature_index,,,,
0,ENSG00000186092,OR4F5,Gene Expression,reference_GRCh38_100
1,ENSG00000284733,OR4F29,Gene Expression,reference_GRCh38_100
2,ENSG00000284662,OR4F16,Gene Expression,reference_GRCh38_100
3,ENSG00000187634,SAMD11,Gene Expression,reference_GRCh38_100
4,ENSG00000188976,NOC2L,Gene Expression,reference_GRCh38_100
...,...,...,...,...
19965,ENSG00000277856,AC233755.2,Gene Expression,reference_GRCh38_100
19966,ENSG00000275063,AC233755.1,Gene Expression,reference_GRCh38_100
19967,ENSG00000271254,AC240274.1,Gene Expression,reference_GRCh38_100
19968,ENSG00000277475,AC213203.4,Gene Expression,reference_GRCh38_100
19969,ENSG00000268674,AC213203.1,Gene Expression,reference_GRCh38_100

In [25]:
adata114.uns

{'cellranger': {'assembly_label': 'GRCh38',
  'cloupe_file': '/ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/pbmc_1k_v3_count_r100/outs/cloupe.cloupe',
  'dataset': 'pbmc_1k_v3',
  'ensembl_release': 100,
  'metrics_summary': {'Estimated Number of Cells': '1,221',
   'Fraction Reads in Cells': '95.6%',
   'Mean Reads per Cell': '54,547',
   'Median Genes per Cell': '2,985',
   'Median UMI Counts per Cell': '9,188',
   'Number of Reads': '66,601,887',
   'Q30 Bases in Barcode': '94.1%',
   'Q30 Bases in RNA Read': '90.2%',
   'Q30 Bases in UMI': '92.7%',
   'Reads Mapped Antisense to Gene': '7.9%',
   'Reads Mapped Confidently to Exonic Regions': '53.9%',
   'Reads Mapped Confidently to Genome': '93.3%',
   'Reads Mapped Confidently to Intergenic Regions': '8.9%',
   'Reads Mapped Confidently to Intronic Regions': '30.5%',
   'Reads Mapped Confidently to Transcriptome': '74.5%',
   'Reads Mapped to Genome': '96.1%',
   'Sequencing Saturation': '70.7%',
   'Total Genes Detected': '16,419',
   'Valid Barcodes': '97.4%',
   'Valid UMIs': '99.9%'},
  'molecule_info_h5': '/ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/pbmc_1k_v3_count_r100/outs/molecule_info.h5',
  'outs_dir': '/ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/pbmc_1k_v3_count_r100/outs',
  'web_summary_html': '/ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/pbmc_1k_v3_count_r100/outs/web_summary.html'},
 'provenance': {'assembly_label': 'GRCh38',
  'dataset': 'pbmc_1k_v3',
  'ensembl_release': 100,
  'outs_dir': '/ictstr01/groups/ml01/workspace/kemal.inecik/idtrack_experiments/alignments/pbmc_1k_v3/GRCh38_100/pbmc_1k_v3_count_r100/outs'}}

# Analysis

## Running IDTrack

In [ ]:
pass

## Analysis of IDTrack performance

In [ ]:
pass

### Finalized figures

In [ ]:
pass

## Running competing tools

In [ ]:
pass

## Analysis of IDTrack performance

In [ ]:
pass

### Finalized figures

In [ ]:
pass